SELECT 
-- from raw orders
o.ORDERID,
o.ORDERDATE,
o.SHIPDATE,
o.SHIPMODE,
o.ORDERSELLINGPRICE - o.ORDERCOSTPRICE AS ORDERPROFIT,
o.ORDERSELLINGPRICE,
o.ORDERCOSTPRICE,
-- from raw customer
c.CUSTOMERNAME,
C.SEGMENT,
C.COUNTRY,
-- from raw product
p.CATEGORY,
p.PRODUCTNAME,
P.SUBCATEGORY

FROM {{ref('RAW_ORDERS')}} AS o
left join {{ref('RAW_CUSTOMER')}} AS c
ON o.CUSTOMERID = c.CUSTOMERID

left join {{ ref('RAW_PRODUCT') }} AS p
ON o.PRODUCTID= p.PRODUCTID
